color0 #3f4946
color1 #ffb4ab
color2 #84d6c2
color3 #b1ccc4
color4 #aacbe4
color5 #84d6c2
color6 #b1ccc4
color7 #dee4e0
color8 #89938f
color9 #ffb4ab
color10 #84d6c2
color11 #b1ccc4
color12 #aacbe4
color13 #84d6c2
color14 #b1ccc4
color15 #dee4e0

cursor                #dee4e0
cursor_text_color     #0e1513
background            #0e1513
foreground            #dee4e0
selection_foreground  #bfc9c4
selection_background  #3f4946
active_border_color   #84d6c2
inactive_border_color #3f4946
url_color             #84d6c2

active_tab_foreground   #00382e
active_tab_background   #84d6c2
inactive_tab_foreground #bfc9c4
inactive_tab_background #3f4946
cursor_trail_color      #bfc9c4
