color0 #1b3036
color1 #fd4663
color2 #67dde4
color3 #5c93d6
color4 #807ce4
color5 #93e7ec
color6 #96bbe9
color7 #f2f3f3
color8 #5f6e6f
color9 #fd4663
color10 #67dde4
color11 #5c93d6
color12 #807ce4
color13 #93e7ec
color14 #96bbe9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #142429
background            #142429
foreground            #f2f3f3
selection_foreground  #afb6b6
selection_background  #1b3036
active_border_color   #67dde4
inactive_border_color #1b3036
url_color             #67dde4

active_tab_foreground   #182425
active_tab_background   #67dde4
inactive_tab_foreground #afb6b6
inactive_tab_background #1b3036
cursor_trail_color      #afb6b6
