color0 #371f1b
color1 #ed5236
color2 #f0725b
color3 #eeb444
color4 #d4ee44
color5 #f49b8a
color6 #f4d08a
color7 #f3f2f2
color8 #716461
color9 #ed5236
color10 #f0725b
color11 #eeb444
color12 #d4ee44
color13 #f49b8a
color14 #f4d08a
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291714
background            #291714
foreground            #f3f2f2
selection_foreground  #b6b0af
selection_background  #371f1b
active_border_color   #f0725b
inactive_border_color #371f1b
url_color             #f0725b

active_tab_foreground   #251a18
active_tab_background   #f0725b
inactive_tab_foreground #b6b0af
inactive_tab_background #371f1b
cursor_trail_color      #b6b0af
