# Hellpaper Configuration File
# Location: ~/.config/hellpaper/hellpaper.conf
# Managed by hyprdesk

[Theme]
# Colors in RGBA format (0 - 255)
# Fully Transparent & Minimal Theme (RGBA)
bg      = 0, 0, 0, 0
idle    = 0, 0, 0, 0
hover   = 49, 50, 68, 140
border  = 137, 180, 250, 255
ripple  = 203, 166, 247, 255
overlay = 0, 0, 0, 0
text    = 0, 0, 0, 0

[Settings]
# Window Dimensions
width = 1280
height = 720

# Wallpaper loading limits
max_wallpapers = 256
max_threads = 8

# Thumbnails and spacing
base_thumb_size = 160
base_padding = 16
border_thickness_bloom = 2.5

# Animations and Physics
anim_speed = 22.0
particle_count = 40
ken_burns_duration = 15.0
max_fps = 144

[Effects]
# Available effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = blur
keypress_effect = none
exit_effect = none
